<a href="https://colab.research.google.com/github/datajcthemax/playdata/blob/main/day10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
10번째 스토리
Numpy 배열 연산과 통계
병원관리 SQL Table 설계 확인하고 발전사항 기록
이번주에 배운내용 정리

다음주의 이야기
Mini Project 과학적인(?) 팀 구성
Pandas 시리즈와 데이터 프레임
데이터프레임 심화
데이터 시각화 - 탐색적 데이터 분석(EDA)
Mini Project(14, 17일)

In [1]:
# 두 배열의 합
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
c

array([5, 7, 9])

In [2]:
# 두 배열의 곱
c = a*b
c

array([ 4, 10, 18])

In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)
print(B)
C = np.dot(A, B)
C

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [4]:
# 전치 행렬
A = np.array([[1, 2], [3, 4]])
print(A)


[[1 2]
 [3 4]]


In [5]:
type(A)

numpy.ndarray

In [6]:
A.T

array([[1, 3],
       [2, 4]])

In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[11,12,13],[14,15,16],[24,25,26]])
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [24, 25, 26]]))

In [8]:
a.shape, b.shape

((2, 3), (3, 3))

In [9]:
np.dot(a,b)

array([[111, 117, 123],
       [258, 273, 288]])

In [10]:
# 전치행렬의 사용 예
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[11,12,13],[14,15,16]])

In [11]:
b.T

array([[11, 14],
       [12, 15],
       [13, 16]])

In [12]:
np.dot(a,b.T)

array([[ 74,  92],
       [182, 227]])

In [13]:
# 역행렬
# np.dot(A,B) = E
# B는 A의 역행렬이다(A는 B의 역행렬)
E = np.eye(3)
E

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# 우리가 아는 사례
# a*b = a
# 3 * b = 3 # b=1

In [15]:
# 브로드캐스팅 예제
A = np.array([[1,2],[3,4]]) 
b = np.array([1,2])
C = A+b
C

array([[2, 4],
       [4, 6]])

Numpy 통계 함수