<a href="https://colab.research.google.com/github/datajcthemax/playdata/blob/main/day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
num = [4,3,1,0,2]

def new_list():
  ans = []
  for i in range(0,len(num)):
    ans.append(num[num[i]])
  return ans

new_list()

[2, 0, 3, 4, 1]

오늘의 미션
1. Numpy 배열 기초
2. Numpy 연습
3. Numpy 활용




In [ ]:
# Numpy 배열 생성

In [ ]:
import numpy as np

a = [1,2,3]
arr1 = np.array(a)
arr1

array([1, 2, 3])

In [ ]:
b = [[1,2,3],
     [4,5,6]]

arr2 = np.array(b)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c = [[[1,2,3],[4,5,6]],[[2,4,6],[10,11,12]]]
arr3 = np.array(c)
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 2,  4,  6],
        [10, 11, 12]]])

In [ ]:
##배열 속성

In [ ]:
arr1, arr2, arr3

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 2,  4,  6],
         [10, 11, 12]]]))

In [ ]:
# shape
print("arr1.shape",arr1.shape)
print("arr2.shape",arr2.shape)
print("arr3.shape",arr3.shape)

arr1.shape (3,)
arr2.shape (2, 3)
arr3.shape (2, 2, 3)


In [ ]:
#Size

In [ ]:
arr1.size, arr2.size, arr3.size

(3, 6, 12)

In [ ]:
#dtype

In [ ]:
arr1 = np.array([1,2,3])
arr1.dtype

dtype('int64')

In [ ]:
arr2 = np.array([1.,2.,3.])
arr2.dtype

dtype('float64')

In [ ]:
arr1_dtype8 = np.array([1,2,3], dtype=np.int8)
arr1_dtype8.dtype

dtype('int8')

In [ ]:
# 이미지 관련된 데이터 int8

In [ ]:
arr1_dtype16 = np.array([1,2,3], dtype=np.int16)
arr1_dtype16.dtype

dtype('int16')

In [ ]:
arr_str = np.array(['엔','코','아'])
arr_str.dtype

dtype('<U1')

ndim

In [ ]:
arr1, arr2, arr3

(array([1, 2, 3]),
 array([1., 2., 3.]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 2,  4,  6],
         [10, 11, 12]]]))

In [ ]:
arr1.ndim, arr2.ndim, arr3.ndim

(1, 1, 3)

배열 생성 함수

In [ ]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [ ]:
ones = np.ones((1,3))
ones

array([[1., 1., 1.]])

In [ ]:
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arange = np.arange(0, 11, 2)
arange

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
arange.ndim # 차원

1

In [ ]:
arange.shape # shape

(6,)

In [ ]:
arange.ndim

1

In [ ]:
tmp = arange.reshape(1,-1)
tmp.ndim, tmp.shape

(2, (1, 6))

In [ ]:
tmp.reshape(-1, 1)

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [ ]:
arange_reshape = arange.reshape(2,3)
arange_reshape

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [ ]:
arange_reshape.reshape(3,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
arange_reshape.reshape(3,-1)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
arange_reshape.reshape(-1, 2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
linspace = np.linspace(0, 1, 5)
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [ ]:
add = arr1+arr2
add

array([5, 7, 9])

In [ ]:
add_ = arr1.reshape(1,-1)+arr2
add_

array([[5, 7, 9]])

In [ ]:
arr1

array([1, 2, 3])

In [ ]:
arr3 = np.array([10])
arr3

array([10])

In [ ]:
arr1+arr3

array([11, 12, 13])

In [ ]:
subtract = arr1 - arr2
subtract

array([-3, -3, -3])

In [ ]:
multiply = arr1 * arr2
multiply

array([ 4, 10, 18])

In [ ]:
divide = arr1 / arr2
divide

array([0.25, 0.4 , 0.5 ])

In [ ]:
dot_product = np.dot(arr1, arr2)
dot_product

32

In [ ]:
arr1,arr2

(array([1, 2, 3]), array([4, 5, 6]))

In [ ]:
arr1=np.array([[1,1,1],[2,2,2]])
arr1

array([[1, 1, 1],
       [2, 2, 2]])

In [ ]:
arr2=np.array([[1,1],[2,2],[3,3]])
arr2

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
matmul_arr = np.matmul(arr1, arr2)

In [ ]:
matmul_arr

array([[ 6,  6],
       [12, 12]])

In [ ]:
np.array([1,2,3])*np.array([10,11,12])

array([10, 22, 36])

In [ ]:
# 리스트에서 사용했던 인덱싱과 슬라이싱 기억해 봅시다
a = [1,2,3,4,5]

In [ ]:
# 인덱싱
a[0]

1

In [ ]:
# 슬라이싱
a[0:1]

[1]

numpy에서의 인덱싱과 슬라이싱

In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
# 인덱싱
a[0]

1

In [ ]:
# 슬라이싱
a[0:1]

array([1])

조건 인덱싱과 팬시 인덱싱

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr>4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [ ]:
# 조건 인덱싱
condition = arr>4

In [ ]:
arr[condition]

array([5, 6, 7, 8, 9])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 팬시 인덱싱
rows = np.array([0,1])
cols = np.array([1,2])
fancy_indexed = arr[rows, cols] 

In [ ]:
fancy_indexed

array([2, 6])

왜 리스트로 하면 되지 numpy를 사용하나요?
list(tuple)
numpy
tensor
image
RedGreenBlue(RGB)로 색상을 표현 (3가지 채널)
GrayScale 흑백 사진 (1가지 채널)
값 영역 0~255
int8 자료형

In [95]:
2*2*2*2*2*2*2*2

256